<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\VerticalSliceArchitecture.Api\VerticalSliceArchitecture.Api.csproj" />
    <ProjectReference Include="..\..\src\VerticalSliceArchitecture.Domain\VerticalSliceArchitecture.Domain.csproj" />
    <ProjectReference Include="..\..\src\VerticalSliceArchitecture.Integrations\VerticalSliceArchitecture.Integrations.csproj" />
    <ProjectReference Include="..\..\src\VerticalSliceArchitecture.Persistence\VerticalSliceArchitecture.Persistence.csproj" />
    <ProjectReference Include="..\..\src\VerticalSliceArchitecture.SharedKernel\VerticalSliceArchitecture.SharedKernel.csproj" />
  </ItemGroup>

</Project>
